cli: CLI Structure
cli: {
    main_command: rust-cli
    first_level_sub_command: first-level-subcommand
    second_level_sub_command: second-level-subcommand
    first_level_flag: --first-level-flag
    second_level_flag: --second-level-flag

    main_command -> first_level_sub_command
    first_level_sub_command -> second_level_sub_command
    first_level_sub_command -> first_level_flag
    second_level_sub_command -> second_level_flag
}